/* HOTEL_LOGICO: */

CREATE TABLE CLIENTE (
    ID_CLIENTE INTEGER PRIMARY KEY NOT NULL,
    NUMERO_RG VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    SEXO CHAR NULL,
    FONE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE RESERVA (
    ID_RESERVA INTEGER PRIMARY KEY NOT NULL,
    DATA_RESERVA DATE NOT NULL,
    DIAS_RESERVA INTEGER NOT NULL,
    FK_ID_CLIENTE INTEGER NOT NULL CONSTRAINT FK_RESERVA_2    FOREIGN KEY (FK_ID_CLIENTE)    REFERENCES CLIENTE (ID_CLIENTE)    ON DELETE CASCADE
);

CREATE TABLE QUARTO (
    ID_QUARTO INTEGER PRIMARY KEY NOT NULL,
    NUMERO INTEGER NOT NULL,
    ANDAR INTEGER NOT NULL,
    FK_ID_TIPO INTEGER NOT NULL CONSTRAINT FK_QUARTO_2    FOREIGN KEY (FK_ID_TIPO)    REFERENCES TIPO_QUARTO (ID_TIPO) ON DELETE CASCADE
);

CREATE TABLE SERVICO (
    ID_SERVICO INTEGER PRIMARY KEY NOT NULL,
    TIPO_SERVICO VARCHAR(30) NOT NULL,
    DESC_SERVICO VARCHAR(100) NOT NULL,
    VALOR_SERVICO NUMERIC(18,2) NOT NULL
);

CREATE TABLE TIPO_QUARTO (
    ID_TIPO INTEGER PRIMARY KEY NOT NULL,
    TIPO VARCHAR NOT NULL,
    DESC_TIPO VARCHAR NOT NULL,
    VALOR_TIPO NUMERIC NOT NULL
);

CREATE TABLE OCUPACAO (
    ID_OCUPACAO INTEGER PRIMARY KEY NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    DATA_SAIDA DATE NULL,
    FK_ID_QUARTO INTEGER NOT NULL CONSTRAINT FK_OCUPACAO_2 FOREIGN KEY (FK_ID_QUARTO) REFERENCES QUARTO (ID_QUARTO),
    FK_ID_RESERVA INTEGER NOT NULL CONSTRAINT FK_OCUPACAO_3    FOREIGN KEY (FK_ID_RESERVA)    REFERENCES RESERVA (ID_RESERVA)
);

CREATE TABLE OCUPACAO_SERVICO (
    FK_ID_OCUPACAO INTEGER CONSTRAINT FK_OCUPACAO_SERVICO_1  FOREIGN KEY (FK_ID_OCUPACAO) REFERENCES OCUPACAO (ID_OCUPACAO) ON DELETE SET NULL,
    FK_ID_SERVICO INTEGER CONSTRAINT FK_OCUPACAO_SERVICO_2  FOREIGN KEY (FK_ID_SERVICO) REFERENCES SERVICO (ID_SERVICO) ON DELETE SET NULL,
    ID_OCUPACAO_SERVICO INTEGER PRIMARY KEY
);
